<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'APP_SECRET' => '1e1326bdd3b1afddd07031f49b44e0d1',
  'DATABASE_URL' => 'mysql://ybkl115c9c5g4lpy:k63lqguaojbw8t8u@k2fqe1if4c7uowsh.cbetxkdyhwsb.us-east-1.rds.amazonaws.com:3306/yljuggjn0jj2ixyc',
);