<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXrc85Nc\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXrc85Nc/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXrc85Nc.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXrc85Nc\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerXrc85Nc\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Xrc85Nc',
    'container.build_id' => '0c092d0d',
    'container.build_time' => 1580355324,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXrc85Nc');
